// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6UpXBKeDaOae-V6TQqt-1LE-SwxAb7fQ',
    appId: '1:740676443655:web:cf7fe60c1cc36a1a2994a2',
    messagingSenderId: '740676443655',
    projectId: 'componentes5c-31707',
    authDomain: 'componentes5c-31707.firebaseapp.com',
    storageBucket: 'componentes5c-31707.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC02YPPFOzwwVA7oCcXSqMejWhuB4QekVA',
    appId: '1:740676443655:android:a93e998c7c21319c2994a2',
    messagingSenderId: '740676443655',
    projectId: 'componentes5c-31707',
    storageBucket: 'componentes5c-31707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_ddiEZ3guhVBhhnXdF0EjpBaZpPNcB8g',
    appId: '1:740676443655:ios:63604ff52648e2c12994a2',
    messagingSenderId: '740676443655',
    projectId: 'componentes5c-31707',
    storageBucket: 'componentes5c-31707.appspot.com',
    iosBundleId: 'com.example.practica3Componentes',
  );
}
